app1/urls.py
from app1.views import *

from django.urls import path

app_name = 'iam'

urlpatterns=[
    path('yashwanth/',yashwanth,name='yashwanth'),
]

app2/urls.py
from app2.views import *

from django.urls import path

app_name = 'life'

urlpatterns=[

    path('respond/',respond,name='respond'),

]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),

]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

#create your views here.

def yashwanth(request):
    return render(request,'yashwanth.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def respond(request):
    return render(request,'respond.html')

templates/respond.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is a respond html</h1>
        <a href="{% url 'iam:yashwanth' %}"><h1>respond response</h1></a>
    </center>
</body>
</html>

templates/yashwanth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is a yashwanth html</h1>
        <a href="{% url 'life:respond' %}"><h1>yashwanth response</h1></a>
    </center>
    
</body>
</html>